Models/Data.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace Cliente.Models
{

    
    
    public class Data
    {
        public string Date { get; set; }
        public float Inflation { get; set; }
        public float CPI { get; set; }
        public float PPI { get; set; }
        public float External_debt { get; set; }
        public float RRM { get; set; }

    }
}

Models/DataPoint.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace Cliente.Models
{
    [DataContract]
    public class DataPoint
    {
        public DataPoint(string x, double y)
        {
            this.X = x;
            this.Y = y;
        }

        //Explicitly setting the name to be used while serializing to JSON.
        [DataMember(Name = "x")]
        public string X = null;

        //Explicitly setting the name to be used while serializing to JSON.
        [DataMember(Name = "y")]
        public Nullable<double> Y = null;
    }
}

Models/ErrorViewModel.cs
using System;

namespace Cliente.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/DatosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Json;
using System.Threading.Tasks;
using Cliente.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestSharp;

namespace Cliente.Controllers
{
    public class DatosController : Controller
    {
        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult Datos()
        {
            return null;
        }

        public string GetReleases(string url)
        {
            var client = new RestClient(url);

            var response = client.Execute(new RestRequest());

            return response.Content;
        }

        public ContentResult JSON_RRM()
        {
            String json_datos = GetReleases("http://modelobernier.azurewebsites.net/datos");

            var dato = JsonConvert.DeserializeObject<List<Data>>(json_datos);

            List<DataPoint> dataPoints = new List<DataPoint>();
            for (var i = 0; i < 4385; i++)
            {
                dataPoints.Add(new DataPoint(dato[i].Date, dato[i].RRM));
            }
            JsonSerializerSettings _jsonSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore };
            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");
        }

        public ContentResult JSON_CPI()
        {
            String json_datos = GetReleases("http://modelobernier.azurewebsites.net/datos");

            var dato = JsonConvert.DeserializeObject<List<Data>>(json_datos);

            List<DataPoint> dataPoints = new List<DataPoint>();
            for (var i = 0; i < 4385; i++)
            {
                dataPoints.Add(new DataPoint(dato[i].Date, dato[i].CPI));
            }
            JsonSerializerSettings _jsonSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore };
            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");
        }

        public ContentResult JSON_INFLATION()
        {
            String json_datos = GetReleases("http://modelobernier.azurewebsites.net/datos");

            var dato = JsonConvert.DeserializeObject<List<Data>>(json_datos);

            List<DataPoint> dataPoints = new List<DataPoint>();
            for (var i = 0; i < 4385; i++)
            {
                dataPoints.Add(new DataPoint(dato[i].Date, dato[i].Inflation));
            }
            JsonSerializerSettings _jsonSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore };
            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");
        }

        public ContentResult JSON_PPI()
        {
            String json_datos = GetReleases("http://modelobernier.azurewebsites.net/datos");

            var dato = JsonConvert.DeserializeObject<List<Data>>(json_datos);

            List<DataPoint> dataPoints = new List<DataPoint>();
            for (var i = 0; i < 4385; i++)
            {
                dataPoints.Add(new DataPoint(dato[i].Date, dato[i].PPI*100));
            }
            JsonSerializerSettings _jsonSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore };
            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");
        }

        public ContentResult JSON_EXTERNAL()
        {
            String json_datos = GetReleases("http://modelobernier.azurewebsites.net/datos");

            var dato = JsonConvert.DeserializeObject<List<Data>>(json_datos);

            List<DataPoint> dataPoints = new List<DataPoint>();
            for (var i = 0; i < 4385; i++)
            {
                dataPoints.Add(new DataPoint(dato[i].Date, dato[i].External_debt));
            }
            JsonSerializerSettings _jsonSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore };
            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Cliente.Models;

namespace Cliente.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PrediccionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.Serialization.Json;
using System.Threading.Tasks;
using Cliente.Models;
using CsvHelper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestSharp;

namespace Cliente.Controllers
{
    public class PrediccionesController : Controller
    {

        public IActionResult Index()
        {
            
            
            return View();
        }

        public IActionResult Predicciones()
        {
            return View();
        }

        public string GetReleases(string url)
        {
            var client = new RestClient(url);

            var response = client.Execute(new RestRequest());

            return response.Content;
        }

        public ContentResult JSON()
        {
            String json_predictions = GetReleases("http://modelobernier.azurewebsites.net/");

            var dato = JsonConvert.DeserializeObject<List<Data>>(json_predictions);

            List<DataPoint> dataPoints = new List<DataPoint>();
            for (var i = 0; i < 30; i++)
            {
                dataPoints.Add(new DataPoint(dato[i].Date, dato[i].RRM));
            }
            JsonSerializerSettings _jsonSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore };
            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");
        }

    }

}

Views/Datos/Index.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <script>
    window.onload = function () {

    var dataPoints = [];
    var dataPointsInflation = [];
    var dataPointsCPI = [];
    var dataPointsPPI = [];
    var dataPointsExternal = [];

    var chart = new CanvasJS.Chart("chartContainer", {
    	animationEnabled: true,
    	theme: "light2",
    	title: {
    		text: "Tasa representativa del cambio COP/USD"
    	},
    	axisY: {
    		title: "En $COP",
    		titleFontSize: 24,
    		includeZero: false
    	},
    	data: [{
    		type: "line",
    		yValueFormatString: "$COP#,###",
    		dataPoints: dataPoints
    	}]
    });

    var chart_inflation = new CanvasJS.Chart("chartContainerInflation", {
    	animationEnabled: true,
    	theme: "light2",
    	title: {
    		text: "Inflation"
    	},
    	axisY: {
    		title: "Porcentaje",
    		titleFontSize: 24,
    		includeZero: false
    	},
    	data: [{
    		type: "line",
    		yValueFormatString: "#,### %",
            dataPoints: dataPointsInflation
    	}]
    });

    var chart_cpi = new CanvasJS.Chart("chartContainerCPI", {
    	animationEnabled: true,
    	theme: "light2",
    	title: {
    		text: "CPI"
    	},
    	axisY: {
    		title: "Puntos representativos",
    		titleFontSize: 24,
    		includeZero: false
    	},
    	data: [{
    		type: "line",
    		yValueFormatString: "#,###",
            dataPoints: dataPointsCPI
    	}]
    });


    var chart_ppi = new CanvasJS.Chart("chartContainerPPI", {
    	    animationEnabled: true,
    	    theme: "light2",
    	    title: {
    		    text: "PPI"
    	    },
    	    axisY: {
    		    title: "Porcentaje",
    		    titleFontSize: 24,
    		    includeZero: false
    	    },
    	    data: [{
    		    type: "line",
    		    yValueFormatString: "#,### %",
                dataPoints: dataPointsPPI
    	    }]
    });

    var chart_external = new CanvasJS.Chart("chartContainerExternal", {
    	    animationEnabled: true,
    	    theme: "light2",
    	    title: {
    		    text: "External Debt"
    	    },
    	    axisY: {
    		    title: "Puntos representativos",
    		    titleFontSize: 24,
    		    includeZero: false
    	    },
    	    data: [{
    		    type: "line",
    		    yValueFormatString: "#,### MMD",
                dataPoints: dataPointsExternal
    	    }]
     });

    function addData(data) {
    	for (var i = 0; i < data.length; i++) {
    		dataPoints.push({
                x: new Date(data[i].x),
    			y: data[i].y
    		});
    	}
    	chart.render();

    }

    function addData2(data) {
    	for (var i = 0; i < data.length; i++) {
            dataPointsInflation.push({
                x: new Date(data[i].x),
    			y: data[i].y
    		});
    	}
        chart_inflation.render();

    }

    function addData3(data) {
    	for (var i = 0; i < data.length; i++) {
            dataPointsCPI.push({
                x: new Date(data[i].x),
    			y: data[i].y
    		});
    	}
        chart_cpi.render();

    }



    function addData4(data) {
    	for (var i = 0; i < data.length; i++) {
            dataPointsPPI.push({
                x: new Date(data[i].x),
    			y: data[i].y
    		});
    	}
        chart_ppi.render();

    }

    function addData5(data) {
    	for (var i = 0; i < data.length; i++) {
            dataPointsExternal.push({
                x: new Date(data[i].x),
    			y: data[i].y
    		});
    	}
        chart_external.render();

    }

    $.getJSON("/Datos/json_rrm", addData);
    $.getJSON("/Datos/json_inflation", addData2);
    $.getJSON("/Datos/json_ppi", addData4);
    $.getJSON("/Datos/json_external", addData5);
    $.getJSON("/Datos/json_cpi", addData3);
    }
    </script>
</head>
<body>
    <hr />
    <div id="chartContainer" style="height: 450px; width: 1200px;"></div>

    <hr />
    <div id="chartContainerInflation" style="height: 450px; width: 1200px;"></div>

    <hr />
    <div id="chartContainerCPI" style="height: 450px; width: 1200px;"></div>

    <hr />
    <div id="chartContainerPPI" style="height: 450px; width: 1200px;"></div>

    <hr />
    <div id="chartContainerExternal" style="height: 450px; width: 1200px;"></div>

    <hr />
    <div id="chartContainer" style="height: 450px; width: 1200px;"></div>
    <script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
    <script src="https://canvasjs.com/assets/script/jquery.canvasjs.min.js"></script>
</body>
</html>             

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pagina de Inicio";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Aprende como hacer predicciones en cualquier divisa con Machine Learning!.
                    <a class="btn btn-default" href="https://colab.research.google.com/drive/1tu__mTiHHJ-SNtj4JK0vRCLMGDg9RWjf">
                        Aprende más
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Aprende como hacer predicciones en cualquier divisa con Machine Learning!.
                    <a class="btn btn-default" href="https://colab.research.google.com/drive/1tu__mTiHHJ-SNtj4JK0vRCLMGDg9RWjf">
                        Aprende más
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.jpg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Aprende como hacer predicciones en cualquier divisa con Machine Learning!.
                    <a class="btn btn-default" href="https://colab.research.google.com/drive/1tu__mTiHHJ-SNtj4JK0vRCLMGDg9RWjf">
                        Aprende más
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

Views/Predicciones/Index.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <script>
    window.onload = function () {

    var dataPoints = [];

    var chart = new CanvasJS.Chart("chartContainer", {
    	animationEnabled: true,
    	theme: "light2",
    	title: {
    		text: "(Predicción) Tasa representativa del cambio COP/USD"
    	},
    	axisY: {
    		title: "En $COP",
    		titleFontSize: 24,
    		includeZero: false
    	},
    	data: [{
    		type: "line",
    		yValueFormatString: "$COP#,###",
    		dataPoints: dataPoints
    	}]
    });


      
    function addData(data) {
    	for (var i = 0; i < data.length; i++) {
    		dataPoints.push({
                x: new Date(data[i].x),
    			y: data[i].y
    		});
    	}
    	chart.render();
    }

    $.getJSON("/Predicciones/json", addData);

    }
    </script>
</head>
<body>
    <hr />
    <div id="chartContainer" style="height: 450px; width: 1200px;"></div>
    <script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
    <script src="https://canvasjs.com/assets/script/jquery.canvasjs.min.js"></script>
</body>
</html>                              

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Predictor</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Predictor</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Inicio</a></li>
                    <li><a asp-area="" asp-controller="Predicciones" asp-action="Index">Predicciones</a></li>
                    <li><a asp-area="" asp-controller="Datos" asp-action="Index">Datos</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Predictor</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>